name: profileapp
description: "Profile Discovery Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.2

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^15.1.2

  # Network
  dio: ^5.8.0+1

  # Local Storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3

  # Image
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Dependency Injection
  get_it: ^8.0.3

  # Utils
  uuid: ^4.5.1
  intl: ^0.20.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
